METHOD:
  method: 'ALPHA-TIM'
  temp: 15
  loss_weights: [1.0, 1.0, 1.0]  # [Xent, H(Y), H(Y|X)]
  lr_alpha_tim: 1e-4
  iter: 1000
  entropies: ['Shannon', 'Alpha', 'Alpha'] # [Xent, H(Y), H(Y|X)]
  alpha_values: [5.0, 5.0, 5.0] # [Xent, H(Y), H(Y|X)]
  use_tuned_alpha_values: True